// Generated by scripts/encrypt.js. The salt + verifier are NOT secret;
// only the passphrase (shared by Safal after approving a request) is.
window.LOCK = {
  email: "safbhalerao@gmail.com",
  enc: "assets/work/enc/",
  salt: "tQPIcSENaeSlOn4COHq1kA==",
  iter: 150000,
  verifier: "ls+1ULNqPttq3W4mN9w4Q/sFOyWGWx6nEFVMgeemCzlfNijGCGZAVgaSd+p50w=="
};
