// Generated by scripts/encrypt.js. The salt + verifier are NOT secret;
// only the passphrase (shared by Safal after approving a request) is.
window.LOCK = {
  email: "safbhalerao@gmail.com",
  enc: "assets/work/enc/",
  salt: "+/7YV8snirOeipgm3EE68g==",
  iter: 150000,
  verifier: "HLkT0gAeFQ44nG9z7tIifMUcZbTZ97nTDNieDaS3odshhRf9vrtV5mhpaB8EYw=="
};
