// Encrypt the work files (screenshots + case-study PDF) with AES-GCM.
// The passphrase is supplied via the PASSPHRASE env var and is NEVER written
// to disk. Only the ciphertext (assets/work/enc/*.enc) and the public salt /
// verifier (js/lock-config.js) are committed.
//
//   PASSPHRASE="your phrase" node scripts/encrypt.js
//
// Re-run with a new PASSPHRASE (and the original images present locally) to
// rotate the passphrase.
const fs = require("fs");
const path = require("path");
const { webcrypto } = require("crypto");
const subtle = webcrypto.subtle;

const PASS = process.env.PASSPHRASE;
if (!PASS) { console.error("Set PASSPHRASE env var."); process.exit(1); }

const ROOT = path.join(__dirname, "..");
const WORK = path.join(ROOT, "assets", "work");
const ENC = path.join(WORK, "enc");
const ITER = 150000;
const KEEP_PLAIN = new Set(["paper.png", "og-image.png"]); // not work files
const PDF = "data-annotation-casestudy.pdf";

(async () => {
  fs.mkdirSync(ENC, { recursive: true });
  const salt = webcrypto.getRandomValues(new Uint8Array(16));
  const base = await subtle.importKey("raw", new TextEncoder().encode(PASS), "PBKDF2", false, ["deriveKey"]);
  const key = await subtle.deriveKey(
    { name: "PBKDF2", salt, iterations: ITER, hash: "SHA-256" },
    base, { name: "AES-GCM", length: 256 }, false, ["encrypt"]);

  async function enc(buf) {
    const iv = webcrypto.getRandomValues(new Uint8Array(12));
    const ct = new Uint8Array(await subtle.encrypt({ name: "AES-GCM", iv }, key, buf));
    const out = new Uint8Array(iv.length + ct.length);
    out.set(iv, 0); out.set(ct, iv.length);
    return out;
  }

  const files = fs.readdirSync(WORK)
    .filter((f) => /\.(jpe?g|png)$/i.test(f) && !KEEP_PLAIN.has(f));
  if (fs.existsSync(path.join(WORK, PDF))) files.push(PDF);

  let n = 0;
  for (const f of files) {
    const buf = fs.readFileSync(path.join(WORK, f));
    fs.writeFileSync(path.join(ENC, f + ".enc"), Buffer.from(await enc(buf)));
    n++;
  }

  const verifier = await enc(new TextEncoder().encode("safal-portfolio-ok"));
  const b64 = (u) => Buffer.from(u).toString("base64");
  const config =
`// Generated by scripts/encrypt.js. The salt + verifier are NOT secret;
// only the passphrase (shared by Safal after approving a request) is.
window.LOCK = {
  email: "safbhalerao@gmail.com",
  enc: "assets/work/enc/",
  salt: "${b64(salt)}",
  iter: ${ITER},
  verifier: "${b64(verifier)}"
};
`;
  fs.writeFileSync(path.join(ROOT, "js", "lock-config.js"), config);
  console.log("Encrypted " + n + " files -> assets/work/enc/  (config -> js/lock-config.js)");
})();
